name: Validate, Test and Build
on: push
jobs:  
  # Run unit tests on all platforms/versions of node
  build:
    name: Unit tests
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.5
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
      - name: Installing Modules
        run: yarn install
      - name: Running Prettier
        run: yarn test:prettier
      - name: Running ESLint
        run: yarn test:lint
      - name: Building Libraries and Packages
        run: yarn build
      - name: Running Unit Tests
        run: yarn test:unit --max-workers ${{ steps.cpu-cores.outputs.count }}
